spring:
  datasource:
    url: jdbc:mysql://ls-d6bcb5e8ba5393fa2f5cc92a4acb15f95235b4e5.cafk1c3rx5bo.ap-south-1.rds.amazonaws.com/western
    username: dbmasteruser
    password: kT1Iv[_~4yB=73JO7QP1tmEkR_yRGi8*
  mail:
    host: smtp.gmail.com
    username: abhijithdigerman@gmail.com
    port: '587'
    properties:
      mail:
        smtp:
          starttls:
            enable: 'true'
          auth: 'true'
    password: reygjpbluaixdsin
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
      resolve-lazily: 'false'
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update


  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html


    resources:
      static-locations: classpath:/static/

logging:
  level:
    javax:
      mail: DEBUG
    org:
      springframework:
        mail: DEBUG
razorpay:
  apiKey: rzp_test_Vv4K0xZB1OflgS
  apiSecret: t8dvwBA9ChCi6fjQRTs8cpCJ


demo:
  value: Hello_World
